### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gabriel-maxx** [KooroshRZ/WindowsDLLInjector#4]
hello I would like to know how I do it if I want to use a custom dll for example one that I generated in metasploit/cobalt strike?

**Comment by KooroshRZ** [comment]
> hello I would like to know how I do it if I want to use a custom dll for example one that I generated in metasploit/cobalt strike?

Hello
You can just change the variable `DllPath` in [Injector.cpp](https://github.com/KooroshRZ/Windows-DLL-Injector/blob/master/Injector/src/Injector.cpp) file and rebuild the code in visual studio.

**Comment by gabriel-maxx** [comment]
@KooroshRZ thanks i tested it and it worked but i have one last question about "smss.exe", you said "RtlCreatUserThread" injection method works on smss but when i tried after disabling ppl process protection it dies you can tell me what's going on?

**Comment by KooroshRZ** [comment]
> @KooroshRZ thanks i tested it and it worked but i have one last question about "smss.exe", you said "RtlCreatUserThread" injection method works on smss but when i tried after disabling ppl process protection it dies you can tell me what's going on?

I'm not sure but maybe in recent windows build numbers (1909, 2004, ...) it won't work because of security mechanisms.
I haven't tested this within a long time but I think that's the reason.
BTW, How about `NtCreateThread` method on `smss.exe` process?
And also Don't forget to execute the `injector.exe` in `Run as Admin` mode because the `EscalatePrivilege` must be successfully executed before injecting inside system processes.

**Comment by gabriel-maxx** [comment]
> > @KooroshRZ thanks i tested it and it worked but i have one last question about "smss.exe", you said "RtlCreatUserThread" injection method works on smss but when i tried after disabling ppl process protection it dies you can tell me what's going on?
> 
> I'm not sure but maybe in recent windows build numbers (1909, 2004, ...) it won't work because of security mechanisms. I haven't tested this within a long time but I think that's the reason. BTW, How about `NtCreateThread` method on `smss.exe` process? And also Don't forget to execute the `injector.exe` in `Run as Admin` mode because the `EscalatePrivilege` must be successfully executed before injecting inside system processes.

so i tried with all the methods and they all had the same effect the process died but before i could try i had to disable the "ppl" and also the critical process because otherwise it gives me access denied(ppl) and BSOD the critical process...

So what kind of protection do you think is holding me back? can i disable?

**Comment by KooroshRZ** [comment]
> > > @KooroshRZ thanks i tested it and it worked but i have one last question about "smss.exe", you said "RtlCreatUserThread" injection method works on smss but when i tried after disabling ppl process protection it dies you can tell me what's going on?
> > 
> > 
> > I'm not sure but maybe in recent windows build numbers (1909, 2004, ...) it won't work because of security mechanisms. I haven't tested this within a long time but I think that's the reason. BTW, How about `NtCreateThread` method on `smss.exe` process? And also Don't forget to execute the `injector.exe` in `Run as Admin` mode because the `EscalatePrivilege` must be successfully executed before injecting inside system processes.
> 
> so i tried with all the methods and they all had the same effect the process died but before i could try i had to disable the "ppl" and also the critical process because otherwise it gives me access denied(ppl) and BSOD the critical process...
> 
> So what kind of protection do you think is holding me back? can i disable?

If windows block it from being injected, there should be usually no way to inject code from other processes through normal ways.
However, there are still other techniques for example using `COM` method.
I have not implemented for protected processes but you can check this [link](https://googleprojectzero.blogspot.com/2018/10/injecting-code-into-windows-protected.html) from Google ProjectZero.

**Comment by gabriel-maxx** [comment]
@KooroshRZ thank's for your time
